### ISSUE TITLE
This is not so much a issue I just wanted you to be aware you can update your supported server versions

### ISSUE THREAD

**Issue by john1234brown** [UknownGino/ModdedIntegration#11]
I've tested your plugin on a mohist server and it works perfectly fine running server version 1.12.2
Btw so you can update your readme.md to include that you can either use Magma or Mohist :D

**Comment by atferrys** [comment]
Thanks, I've updated it in https://github.com/UknownGino/ModdedIntegration/commit/b17447c5a5df9801d1694e21ebb5e0f36fc5911f
