### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by TheOriginalGolem** [UknownGino/ModdedIntegration#2]
I've used this before on an older version of magma and essentialsx, but now its not working, its not even being loaded by magma so not sure what is affecting it.

Magma version: cedb421b
Essentialsx version: EssentialsX-2.20.0-dev+5-d891268
Forge version: 2860

**Comment by UeberallGebannt** [comment]
Logs please

**Comment by TheOriginalGolem** [comment]
https://mclo.gs/ivrXD5k

**Comment by UknownGino** [comment]
What version of ModdedIntegration are you using?

**Comment by TheOriginalGolem** [comment]
The latest 1.3

**Comment by UknownGino** [comment]
Can you tell me what modpack are you using? So I can try to reproduce the issue.
Oh and check that the plugin jar file isn't corrupted

**Comment by TheOriginalGolem** [comment]
I have downloaded the jar multiple times to make sure it wasnt corrupted, link to the pack: https://www.curseforge.com/minecraft/modpacks/bruv-network-war

Make sure to remove the kinetic anticheat mod, as it will prevent you from connecting to a server.

**Comment by UknownGino** [comment]
Ok, there seems to be an issue with newer magma builds that refuses to load plugins with no META-INF manifest. I'll update the repo and the releases asap

**Comment by TheOriginalGolem** [comment]
Thank you again for this amazing plugin!

**Comment by UknownGino** [comment]
I've updated the artifact in the latest release and added a note in the description, re-download it and it should work.
Thank you for reporting the issue. :)
